/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Computer.glb -t -T 
Files: Computer.glb [179.58KB] > Computer-transformed.glb [66.97KB] (63%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Comp_Mouse: THREE.Mesh
    System_unit: THREE.Mesh
  }
  materials: {
    lambert3SG: THREE.MeshStandardMaterial
    initialShadingGroup: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Computer(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Computer-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Comp_Mouse.geometry} material={materials.lambert3SG} />
      <mesh geometry={nodes.System_unit.geometry} material={materials.initialShadingGroup} />
    </group>
  )
}

useGLTF.preload('/Computer-transformed.glb')
