/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Desk.glb -t -T 
Files: Desk.glb [16.63KB] > Desk-transformed.glb [3.04KB] (82%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    desk_1: THREE.Mesh
    desk_2: THREE.Mesh
  }
  materials: {
    wood: THREE.MeshStandardMaterial
    metal: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Desk(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Desk-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.desk_1.geometry} material={materials.wood} />
        <mesh geometry={nodes.desk_2.geometry} material={materials.metal} />
      </group>
    </group>
  )
}

useGLTF.preload('/Desk-transformed.glb')
