/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 DeskLamp.glb -t -T 
Files: DeskLamp.glb [12.83KB] > DeskLamp-transformed.glb [4.76KB] (63%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Light_Desk_1: THREE.Mesh
    Light_Desk_2: THREE.Mesh
    Light_Desk_3: THREE.Mesh
  }
  materials: {
    Black: THREE.MeshStandardMaterial
    LightMetal: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function DeskLamp(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/DeskLamp-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Light_Desk_1.geometry} material={materials.Black} />
        <mesh geometry={nodes.Light_Desk_2.geometry} material={materials.LightMetal} />
        <mesh geometry={nodes.Light_Desk_3.geometry} material={materials.White} />
      </group>
    </group>
  )
}

useGLTF.preload('/DeskLamp-transformed.glb')
