/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Monitor.glb -t -T 
Files: Monitor.glb [44.24KB] > Monitor-transformed.glb [32.25KB] (27%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Monitor: THREE.Mesh
  }
  materials: {
    lambert3SG: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Monitor(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Monitor-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Monitor.geometry} material={materials.lambert3SG} />
    </group>
  )
}

useGLTF.preload('/Monitor-transformed.glb')
