/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Mouse.glb -t -T 
Files: Mouse.glb [925.52KB] > Mouse-transformed.glb [15.36KB] (98%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ComputerMouse_mesh: THREE.Mesh
  }
  materials: {
    ComputerMouse_mat1: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Mouse(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Mouse-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ComputerMouse_mesh.geometry} material={materials.ComputerMouse_mat1} />
    </group>
  )
}

useGLTF.preload('/Mouse-transformed.glb')
