/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Plate.glb -t -T 
Files: Plate.glb [49.78KB] > Plate-transformed.glb [11.11KB] (78%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['498_Plates']: THREE.Mesh
  }
  materials: {
    ['Mat.001']: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Plate(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Plate-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['498_Plates'].geometry} material={materials['Mat.001']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Plate-transformed.glb')
